# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-19 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='das',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_student',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name_student',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='teste',
        ),
    ]
