# Generated by Django 2.0.4 on 2018-04-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=40)),
                ('subject_absence', models.IntegerField(max_length=3)),
                ('number_credits', models.IntegerField(max_length=3)),
                ('status', models.BooleanField(max_length=1)),
            ],
        ),
    ]
